version: '2.0'
services:
  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    ports:
    - 9093:9093
    depends_on:
    - prometheus
  grafana:
    image: grafana/grafana:4.2.0
    container_name: grafana
    ports:
    - 3000:3000
    depends_on:
    - prometheus    
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
    - 9090:9090
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    - --config.file=/etc/alertmanager/alertmanager.yml
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
    depends_on:
    - cadvisor
    
  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    ports:
    - 8080:8080
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
    - redis
  redis:
    image: redis:latest
    container_name: redis
    ports:
    - 6379:6379
