global:
  scrape_interval: 15s
  evaluation_interval: 15s
rule_files:
 - "alert.rules"

scrape_configs:
- job_name: cadvisor
  scrape_interval: 5s
  static_configs:
  - targets:
    - 150.100.100.54:8080
- job_name: dolefrontend
  scrape_interval: 5s
  static_configs:
  - targets:
    - 150.100.100.54:80